#!/bin/bash

# Install & Configure Squeezeslave

# Install required packages
sudo apt-get -y install alsa alsa-tools alsa-utils alsa-oss

# Install squeezeslave
SQUEEZESLAVE=squeezeslave-1.3-390-lnx26.tar.gz
wget https://squeezeslave.googlecode.com/files/$SQUEEZESLAVE
tar xzf $SQUEEZESLAVE
sudo mv squeezeslave-i64 /usr/bin/squeezeslave
rm squeezeslave $SQUEEZESLAVE

# Configure zones. This will need tweaking based on the soundcard.
sudo cat sound-blaster.alsa.conf > /etc/asound.conf

# Start on boot:
# Disable with:
# sudo update-rc.d -f squeezeslave remove
sudo cp squeezeslave-zones.defaults /etc/default/squeezeslave-zones
sudo cp squeezeslave.init /etc/init.d/squeezeslave

sudo chmod 755 /etc/init.d/squeezeslave
sudo update-rc.d squeezeslave defaults